spring:
  datasource:
    url: jdbc:h2:mem:testdb
  flyway:
    baseline-on-migrate: true # initialize the schema history table
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true # Show SQL in logs
    properties:
      hibernate:
        format_sql: true # "pretty print"